#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""生成 sEMG 算法说明 Markdown 文档"""
import os

OUT = r"E:\sEMG_B_Project\docs\算法说明.md"

md = []
a = md.append

a("# sEMG 肌电信号疲劳检测算法说明\n")
a("**基于 Arduino UNO R4 WiFi 的便携式肌肉疲劳监测设备**\n")
a("---\n")

# 目录
a("## 目录\n")
a("1. 项目背景与意义\n")
a("2. 算法整体架构\n")
a("3. 核心算法详解\n")
a("   - 3.1 信号采集与预处理\n")
a("   - 3.2 RMS（均方根）计算\n")
a("   - 3.3 MDF（中值频率）计算\n")
a("   - 3.4 激活度（Activation）计算\n")
a("   - 3.5 疲劳度（Fatigue）计算\n")
a("   - 3.6 信号质量评估\n")
a("4. 创新亮点\n")
a("5. 优点与缺点分析\n")
a("6. 算法参数说明\n")
a("7. 参考文献\n")
a("\n---\n")

# 1
a("## 1. 项目背景与意义\n")
a("肌肉疲劳的实时监测在运动科学、康复医学和人机交互中具有重要意义。")
a("表面肌电信号（sEMG）是一种通过皮肤表面电极采集肌肉电活动的非侵入式技术，已广泛应用于肌肉状态评估。\n")
a("传统 sEMG 疲劳检测设备通常依赖昂贵的专用仪器和计算机端软件，不便携且成本高。")
a("本项目基于 Arduino UNO R4 WiFi 开发了一款便携式 sEMG 疲劳监测设备，具有以下特点：\n")
a("- **低成本**：BOM 成本约 200 元人民币（AD8232 传感器 + UNO R4 WiFi + 电平转换）\n")
a("- **便携**：腕带式设计，可实时在手机微信小程序上查看数据\n")
a("- **云端**：数据通过 WiFi 上传至微信云开发平台，支持历史分析\n")
a("- **自主算法**：固件端实现完整的 RMS、MDF、激活度、疲劳度计算，无需计算机端处理\n")
a("\n---\n")

# 2
a("## 2. 算法整体架构\n")
a("算法运行在 Arduino UNO R4 WiFi（瑞萨 RA4M1 芯片，主频 48MHz，RAM 32KB）上，")
a("采用定时器中断驱动采样，在主循环中完成全部信号处理。\n")
a("**处理流程（8 步）**\n")
a("| 步骤 | 处理内容 | 输出 |\n")
a("|------|---------|------|\n")
a("| 1 | ADC 中断采样（1000Hz） | 原始 sEMG 电压信号 |\n")
a("| 2 | 环形缓冲区管理（512 点） | 滑动数据窗口 |\n")
a("| 3 | RMS 计算（256 点窗口） | 肌肉激活强度（mV） |\n")
a("| 4 | FFT + 功率谱（256 点） | 频谱分布 |\n")
a("| 5 | MDF 计算（中值频率） | 频谱中心位置（Hz） |\n")
a("| 6 | 激活度归一化 | 0～100% |\n")
a("| 7 | 疲劳度计算（MDF 下降率） | 0～100% |\n")
a("| 8 | 信号质量评估 | 0～100 分 |\n")
a("\n**关键设计决策**：由于 RA4M1 的 RAM 仅 32KB，")
a("FFT 使用 256 点（而非 512 点），以减少内存占用。")
a("频谱计算采用自实现定点 FFT（库仑复数旋转因子预计算），避免依赖大型 FFT 库。\n")
a("\n---\n")

# 3
a("## 3. 核心算法详解\n")

a("### 3.1 信号采集与预处理\n")
a("AD8232 传感器输出经 BSS138 电平转换（3.3V ↔ 5V）后，接入 UNO R4 WiFi 的 14 位 ADC（量程 0～3.3V）。")
a("采样由硬件定时器中断驱动，固定 **1000Hz**：\n")
a("```cpp\n")
a("// main.cpp — ADC 定时器配置\n")
a("ADC::adc_timer.begin([]() {\n")
a("  int16_t adcVal = analogRead(ADC_PIN);\n")
a("  gSignalProcessor.isrPushSample(adcVal);\n")
a("}, 1000.0f);  // 1000 Hz\n")
a("```\n")
a("**环形缓冲区设计**：使用 512 点的环形缓冲区（`RING_BUFFER_SIZE = 512`），")
a("写指针由中断上下文更新，读指针由主循环更新。采用 `volatile` 变量保护，避免中断与主循环之间的数据竞争。\n")
a("**DC 偏移去除**：sEMG 信号含有电极与皮肤接触产生的 DC 偏移，计算 RMS 前需去除。")
a("采用窗口内简单均值法（而非去极值均值），因为 256 点已足够稳定，且去极值会破坏时序：\n")
a("$$\n")
a(r"DC_{bias} = \frac{1}{N} \sum_{i=0}^{N-1} x[i]")
a("\n$$\n")
a("其中 N = 256（FFT 窗口大小），x[i] 为 ADC 原始采样值（单位：mV）。\n")

a("### 3.2 RMS（均方根）计算\n")
a("RMS 反映肌肉收缩时的信号总功率，与收缩强度正相关，是激活度归一化的基础。\n")
a("$$\n")
a(r"RMS = \sqrt{\frac{1}{N} \sum_{i=0}^{N-1} (x[i] - DC_{bias})^2}")
a("\n$$\n")
a("- N = 256，对应 256 ms 时间窗口（@1000Hz 采样）\n")
a("- x[i] 为去除 DC 偏移后的交流分量（单位：mV）\n")
a("- RMS 计算使用加窗**前**的原始信号，因为 RMS 反映时域能量，加窗会影响幅值准确性\n")

a("### 3.3 MDF（中值频率）计算\n")
a("MDF（Median Frequency，中值频率）是肌电信号频谱的中心位置，肌肉疲劳时 MDF 会系统性下降。")
a("这是本算法的核心疲劳指标，大量文献已验证其可靠性。\n")
a("**FFT 实现**：使用 256 点实数 FFT（自实现，旋转因子预计算），加 Hamming 窗减少频谱泄露：\n")
a("```\n")
a("w[i] = 0.5 × (1 - cos(2πi / (N-1)))  // Hamming 窗\n")
a("x_windowed[i] = (x[i] - DC_bias) × w[i]\n")
a("```\n")
a("**MDF 定义**：MDF 是使下式成立的频率 f_mdf：\n")
a("$$\n")
a(r"\int_{f_{min}}^{f_{mdf}} P(f) df = \int_{f_{mdf}}^{f_{max}} P(f) df = \frac{1}{2} \int_{f_{min}}^{f_{max}} P(f) df")
a("\n$$\n")
a("- P(f) 为功率谱密度\n")
a("- f_min = 10 Hz，f_max = 250 Hz（肌电信号有效频谱范围）\n")
a("\n**MDF 计算步骤**：\n")
a("1. 计算功率谱：P[k] = (Re[k]² + Im[k]²) / N，k = 0 ～ N/2-1\n")
a("2. 计算总功率：P_total = Σ P[k]（k 对应 10～250 Hz）\n")
a("3. 若 P_total < 10⁻¹²，视为信号太弱，返回 -1（跳过本次）\n")
a("4. 累积功率，找到使累积功率 ≥ 0.5 × P_total 的 bin\n")
a("5. 线性插值获得精确 MDF 值\n")
a("\n**EMA 平滑**：原始 MDF 值逐帧波动较大，采用指数移动平均（EMA）平滑：\n")
a("$$\n")
a(r"MDF_{current} = MDF_{last} \times (1 - \alpha) + MDF_{raw} \times \alpha")
a("\n$$\n")
a("| 信号状态 | α 值 | 设计理由 |\n")
a("|---------|----------|---------|\n")
a("| 收缩期 / MDF 下降 | 0.35 | 快速跟踪频谱变化，避免滞后 |\n")
a("| 稳态期（>10 帧） | 0.15 | 抑制逐帧抖动，输出平滑 |\n")
a("| 启动过渡（<10 帧） | 0.5→0.15 线性过渡 | 避免初始值偏差导致长时间收敛 |\n")

a("### 3.4 激活度（Activation）计算\n")
a("激活度将实时 RMS 归一化到 0～100%，直观反映肌肉收缩强度。\n")
a("$$\n")
a(r"A(\%) = \text{clamp}\left( \frac{RMS_{current} - RMS_{relax}}{RMS_{active} - RMS_{relax}} \times 100\%,  0, 100 \right)")
a("\n$$\n")
a("- RMS_relax：校准得到的放松状态 RMS（10 秒静息均值）\n")
a("- RMS_active：校准得到的主动收缩 RMS（15 秒最大收缩峰值）\n")
a("- **物理意义**：A = 0% 表示完全放松，A = 100% 表示达到了校准时的最大收缩强度。\n")

a("### 3.5 疲劳度（Fatigue）计算\n")
a("疲劳度是本算法的核心输出，基于 MDF 下降幅度计算，归一化到 0～100%。\n")
a("**公式**：\n")
a("$$\n")
a(r"F_{raw}(\%) = \text{clamp}\left( \frac{MDF_{baseline} - MDF_{current}}{MDF_{baseline}} \times 100\%,  0, 100 \right)")
a("\n$$\n")
a("- MDF_baseline：**动态基线**，取本次收缩开始时的 MDF 值（A 从 <20% 跨越到 >20% 时捕获）\n")
a("- 若无可用的动态基线，则使用校准得到的 MDF_relax\n")
a("\n**EMA 平滑**：疲劳度变化是缓慢的生理过程（10～60 秒时间尺度），")
a("使用 α = 0.1 的 EMA 平滑：\n")
a("$$\n")
a(r"F_{smoothed}(t) = F_{smoothed}(t-1) \times 0.9 + F_{raw}(t) \times 0.1")
a("\n$$\n")
a("**动态基线设计亮点**：传统方法使用校准时的 MDF_relax 作为固定基线，但 MDF 存在日间漂移")
a("（电极位置变化、皮肤阻抗变化等）。本算法采用「每次收缩独立基线」：\n")
a("- 每次肌肉收缩开始时（激活度从 <20% 上升到 >20%），自动捕获当前 MDF 作为本次收缩的基线\n")
a("- 这样即使电极有轻微位移，也能正确反映本次收缩内的疲劳趋势\n")
a("- 避免了固定基线导致的日间不可比问题\n")

a("### 3.6 信号质量评估\n")
a("信号质量（0～100 分）实时反映当前 sEMG 信号是否可信，用于用户界面提示用户调整电极位置。\n")
a("**评分规则**：\n")
a("- **RMS 得分**（35 分）：收缩期 RMS 在 0.1～5 mV 为高质量；放松期 RMS < 0.5 mV 为高质量\n")
a("- **MDF 有效性**（35 分）：MDF 在 [10, 250] Hz 范围内得满分\n")
a("- **连续性**（30 分）：过去 50 帧中 MDF 有效帧占比 × 30\n")
a("\n---\n")

# 4
a("## 4. 创新亮点\n")
a("本项目的算法设计有以下创新点，适合作为高中生科创项目的亮点展示：\n")

a("### 亮点一：基于 MDF 的动态基线疲劳检测\n")
a("传统 sEMG 疲劳检测使用校准时的 MDF 作为固定基线，存在日间漂移问题。")
a("本算法创新地采用「每次收缩独立基线」策略：\n")
a("- 当激活度从 <20% 跨越到 >20% 时，自动捕获当前 MDF 作为本次收缩的基线\n")
a("- 这样即使电极有轻微位移，也能正确反映本次收缩内的疲劳趋势\n")
a("- 该设计提高了算法的实用性和长期稳定性\n")
a("\n")

a("### 亮点二：自适应 EMA 平滑参数\n")
a("MDF 的 EMA 平滑参数 α 不是固定值，而是根据信号状态自适应调整。")
a("固定 α 的 EMA 是常见做法，但本算法根据生理含义自适应调整 α，")
a("这是一个体现「算法针对性设计」的亮点，适合在答辩中展示。\n")

a("### 亮点三：极低资源的嵌入式实现\n")
a("Arduino UNO R4 WiFi 仅有 32KB RAM 和 48MHz 主频，在这样的限制下实现实时 FFT + MDF 计算是一个工程亮点：\n")
a("- FFT 旋转因子预计算并存储在 BSS 段（`static` 数组），避免每次计算重新生成\n")
a("- 使用 256 点 FFT（而非 512 点），在满足频率分辨率的同时控制 RAM 占用\n")
a("- 环形缓冲区设计避免大数组的栈分配（RA4M1 主栈仅 1KB）\n")
a(f"- 固件编译后 RAM 使用率约 **58.7%**（约 19KB / 32KB），在严格限制下成功实现全部功能\n")

a("### 亮点四：完整的本地 + 云端数据闭环\n")
a("固件端完成全部算法计算，结果（RMS、MDF、激活度、疲劳度）通过 WiFi 每 3 秒上传至微信云开发平台，")
a("用户可在微信小程序上实时查看，并支持历史数据查询。\n")
a("\n---\n")

# 5
a("## 5. 优点与缺点分析\n")

a("### 5.1 优点\n")
a("| 优点 | 说明 | 学术/实用价值 |\n")
a("|------|------|--------------|\n")
a("| 实时性强 | 固件端 10Hz 计算频率，延迟 < 100ms | 适合运动中的实时反馈 |\n")
a("| 低功耗便携 | 腕带式设计，USB 供电，可长时间监测 | 适合运动科学和康复场景 |\n")
a("| MDF 动态基线 | 每次收缩自动重新校准基线 | 提高长期使用的稳定性 |\n")
a("| 自适应 EMA | 根据信号状态调整平滑参数 | 兼顾响应速度和稳定性 |\n")
a("| 信号质量指示 | 实时评估信号质量，提示用户调整电极 | 提高数据可靠性 |\n")
a("| 成本极低 | BOM 约 200 元，远低于商用 sEMG 设备 | 适合教育推广 |\n")
a("| 云端数据 | 微信小程序 + 云开发，无需安装 App | 用户友好，数据可回溯 |\n")

a("\n### 5.2 缺点与局限性\n")
a("| 缺点 | 原因 | 改进方向 |\n")
a("|------|------|---------|\n")
a("| 频率分辨率有限 | 256 点 FFT @ 1000Hz → ~3.9 Hz/bin | 增加 FFT 点数（需更多 RAM） |\n")
a("| MDF 计算依赖频谱质量 | 电极接触不良时功率谱异常 | 已通过信号质量评估缓解 |\n")
a("| 校准需要主动配合 | 用户需完成 10s 放松 + 15s 最大收缩 | 可考虑无校准模式 |\n")
a("| 单通道 sEMG | 仅采集一块肌肉 | 硬件扩展（多路 ADC） |\n")
a("| 疲劳度需主观验证 | MDF 下降与主观疲劳的相关性 | 下一步：招募受试者做对照实验 |\n")
a("| UNO R4 WiFi 算力限制 | 无法运行更复杂的频域特征 | 升级到 STM32 或 ESP32 |\n")
a("\n---\n")

# 6
a("## 6. 算法参数说明\n")
a("以下参数可在固件代码中调整，以适应不同应用场景：\n")
a("| 参数 | 当前值 | 说明 |\n")
a("|------|--------|------|\n")
a("| FFT 窗口大小 | 256 点 | 越大频率分辨率越高，但 RAM 占用越多 |\n")
a("| 采样率 | 1000 Hz | 由 ADC 定时器决定，满足 Nyquist 定理 |\n")
a("| MDF 频率范围 | 10～250 Hz | 肌电信号有效频谱范围 |\n")
a("| 激活度收缩阈值 | RMS > 2×RMS_relax | 判定肌肉是否处于收缩状态 |\n")
a("| 动态基线捕获阈值 | 激活度 > 20% | 触发基线更新的激活度阈值 |\n")
a("| MDF EMA α（收缩） | 0.35 | 收缩期 MDF 平滑参数 |\n")
a("| MDF EMA α（稳态） | 0.15 | 稳态 MDF 平滑参数 |\n")
a("| 疲劳度 EMA α | 0.1 | 疲劳度输出平滑参数 |\n")
a("| 信号质量窗口 | 50 帧 | 质量评估的滑动窗口大小 |\n")
a("\n---\n")

# 7
a("## 7. 参考文献\n")
a("1. De Luca CJ. The use of surface electromyography in biomechanics. *Journal of Applied Biomechanics*, 1997, 13(2):135-163.\n")
a("2. Merletti R, Knaflitz M, De Luca CJ. Myoelectric manifestations of fatigue in voluntary and electrically elicited contractions. *Journal of Applied Physiology*, 1990, 69(5):1810-1820.\n")
a("3. Merletti R, Parker PA. *Electromyography: Physiology, Engineering, and Non-Invasive Applications*. IEEE Press/Wiley, 2004.\n")
a("4. Cifrek M, Medved V, Tonković S, Ostojić S. Surface EMG based muscle fatigue evaluation in biomechanics. *Clinical Biomechanics*, 2009, 24(4):327-340.\n")
a("5. González-Izal M, Malanda A, Gorostiaga E, Izquierdo M. Electromyographic models to assess muscle fatigue. *Journal of Electromyography and Kinesiology*, 2012, 22(4):501-512.\n")
a("6. Arduino UNO R4 WiFi 官方文档. https://docs.arduino.cc/hardware/uno-r4-wifi/\n")
a("7. AD8232 单导联心率监测芯片数据手册. Analog Devices.\n")

a("\n---\n")
a("## 附录：核心公式汇总\n")
a("| 符号 | 公式 | 说明 |\n")
a("|------|------|------|\n")
a("| RMS | √(1/N)Σ(x[i] - DC_bias)² | 肌肉激活强度（mV） |\n")
a("| MDF | ∫P(f)df (f_min→MDF) = 0.5×P_total | 频谱中心频率（Hz） |\n")
a("| 激活度 A | clamp((RMS - RMS_r) / (RMS_a - RMS_r) × 100, 0, 100) | 归一化收缩强度（%） |\n")
a("| 疲劳度 F | clamp((MDF_bl - MDF_cur) / MDF_bl × 100, 0, 100) | 基于 MDF 下降的疲劳指数（%） |\n")
a("| 疲劳度平滑 | F(t) = F(t-1)×0.9 + F_raw(t)×0.1 | EMA 平滑输出 |\n")
a("\n注：RMS_r = 放松状态 RMS，RMS_a = 主动收缩 RMS，")
a("MDF_bl = 动态基线或 MDF_relax，N = 256。\n")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("".join(md))

print("[OK] 算法说明 Markdown 已生成：")
print("    " + OUT)
print("")
print("将 Markdown 转为 Word 的方法：")
print("  方法1（推荐）：用 Word 打开 .md 文件，另存为 .docx")
print("  方法2：安装 pandoc 后执行：")
print('    pandoc "' + OUT + '" -o sEMG_算法说明文档.docx --standalone')
print("  方法3：将文本内容复制到 Word 中手动排版")
